### ISSUE TITLE
expect matchers return type is not a Promise in async mode

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/expect-webdriverio#167]
### Environment

**`expect-webdriverio` version**: 1.2.3
**WebdriverIO version**: 6.4.1
**Test Framework**: mocha (jest/jasmine/mocha/cucumber/etc)
**async/sync**: async (is `@wdio/sync` used? - No)

### Description
expect matchers return type is not a Promise

![image](https://user-images.githubusercontent.com/25589559/91039688-4da76200-e60d-11ea-83e5-0e2b2cd5dea2.png)

### Additional Information
Jasmine users should not be affected as far as [expectAsync](https://jasmine.github.io/api/3.4/global.html#expectAsync) is used in async mode.

**Comment by mgrybyk** [comment]
I believe this one should be fixed by https://github.com/webdriverio/expect-webdriverio/pull/122

I guess we should release `expect-webdriverio` to have it @christian-bromann ?

**Comment by christian-bromann** [comment]
@mgrybyk yeah, it seems we missed to release.

Would you mind releasing a new version?

**Comment by mgrybyk** [comment]
may you please help to release it? My local environment is not configured for that, don't want to mess up with something

**Comment by christian-bromann** [comment]
I released `v1.3.0`

**Comment by kishan-patel13** [comment]
@christian-bromann, I am using `v2.0.1` and still facing the same issue 
**"expect matchers return type is not an Promise in Async mode"**
I'm using webdriverIO with async mode

#### pacakges:
- expect `v26.6.2`
- expect-webdriverio `v2.0.1`
- @wdio/mocha-framework `v7.3.0`
- webdriverio `v.7.3.0`
- wdio-chromedriver-service `v7.0.0`
- chromedriver `v90.0.1`


I have also tried by upgrading the version of expect-webdriverio to `v3.1.0` but still no luck.

**Comment by mgrybyk** [comment]
The expect webdrverio is integrated to webdriverio since v7.
Most likely you haven't upgraded or installed packages correctly, and your package lock json file is now broken.
Remove expect and expect webdriverio from from package json, try reinstalling packages from scratch

**Comment by kishan-patel13** [comment]
Thanks @mgrybyk for the reply,

I have performed following steps as you suggested:
- Removed the expect and expect-webdriverio from package.json
- Removed the package-lock.json and node_modules folder
- Re-install node packages

Still facing the same issue

#### Screenshots
- VS Code suggestion
![image](https://user-images.githubusercontent.com/65718497/123053981-0e5ec300-d422-11eb-8fe2-d057763295a2.png)

- expect-webdriverio types
![image](https://user-images.githubusercontent.com/65718497/123054132-32220900-d422-11eb-96c8-44f77d895340.png)

Is there still some problem in package-lock.json?

**Comment by mgrybyk** [comment]
The types looks up to date. I think I got your point now

**Comment by dons20** [comment]
Why is this closed? I recently migrated a project to async mode, and my editor is not inferring that the included `expect` package returns a promise. When I try to clean up invalid await calls, it inadvertently removes those as well. This should be re-opened.

**Comment by christian-bromann** [comment]
@dons20 you are commenting on a two year old issue which has been resolved. If you experience something similar please create a new issue with a reproducible example or even better provide a PR with a fix.
